### ISSUE TITLE
Unknown type taken as array

### ISSUE THREAD

**Issue by mc3** [python-postgres/fe#103]
Given this stored proc:
```
CREATE FUNCTION add_altname(the_cert_name citext, the_altname citext) RETURNS void
```
citext is an extension for case-insensitive text matches.
[(https://www.postgresql.org/docs/12/citext.html)]
Trying to call the proc so:
```
   add_altname = db_handle.proc('add_altname(citext, citext)')
   add_altname('pipapo', 'dummy')
```
Gives:
```
       add_altname = db_handle.proc('add_altname(citext, citext)')

tests/conftest.py:211: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/py_env/p38/lib/python3.8/site-packages/postgresql/driver/pq3.py:2345: in proc
    sp = StoredProcedure(proc_id, self)
/usr/local/py_env/p38/lib/python3.8/site-packages/postgresql/driver/pq3.py:1918: in __init__
    ', '.join([
/usr/local/py_env/p38/lib/python3.8/site-packages/postgresql/driver/pq3.py:1919: in <listcomp>
    '$%d::%s' %(x, database.typio.sql_type_from_oid(proargs[x]))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = postgresql.types.Array([596664, 596664]), item = 2

    def __getitem__(self, item):
    	if self.ndims < 2:
    		# Array with 1dim is more or less a list.
>   		return self._elements[item]
E     IndexError: list index out of range

/usr/local/py_env/p38/lib/python3.8/site-packages/postgresql/types/__init__.py:509: IndexError

```
More complex problems happen with enums, defined in pgsql: (proc signature not recognized)
How to convince py-postgresql to simply pass unknown types as TEXT ?

Any help appreciated.

**Comment by mc3** [comment]
Workaround:
Using
```
db_handle.query("SELECT * FROM add_altname('pipapo'::TEXT::citext, 'dummy'::TEXT::citext)")
```
works as expected.

**Comment by jwp** [comment]
Yeah, that's the way to solve most issues with unrecognized types.

You can use the parameterized form as well:
`ps = db.prepare("SELECT * FROM add_altname($1::text::citext, $2::text::citext)")`
`ps('pipapo', 'dummy')`

> How to convince py-postgresql to simply pass unknown types as TEXT ?

It's preferable to explicitly cast. While irrelevant to citext, given the case that an extension type eventually makes it as a builtin, it is possible that type I/O methods would be provided for it. Such an occurrence would likely break existing usage of the type.

Alternatively, if some type protocol resolution method (e.g. pg_type.typprotocol or some community recognized convention) were to be implemented, the unqualified form would be subject to any new type I/O methods..
