### ISSUE TITLE
How to get list instead of postgresql.types.Array

### ISSUE THREAD

**Issue by seidlmic** [python-postgres/fe#107]
Hello, I am not sure if there is some control for data type conversion. Because of JSON compatibility I would like to have a list in Row object instead of postgresql.types.Array instance. Is it possible to get this behaviour or I should detect and convert data manually?

**Comment by jwp** [comment]
You can override the type I/O method on a per-connection basis, but I would not advise it for this case. If you are targeting JSON and only JSON, I'd recommend looking into packing it as JSON on the server side with SQL. (Haven't been doing much PostgreSQL work lately so I'm not sure how involved this is for your case with ARRAYs)

**Comment by jwp** [comment]
However, if you really want lists, I think your best option may be to subclass postgresql.driver.pq3.TypeIO and override the `array_from_parts` method.

It should look something like this:

```python
# untested code ahead
from postgresql.driver import pq3
class LocalTypeIO(pq3.TypeIO):
    def array_from_parts(self, parts):
        return parts[0] # The "elements" index.

# Optionally update the default driver instance used by postgresql.open.
from postgresql import driver
driver.default = pq3.Driver(typio=LocalTypeIO)
```

**Comment by jwp** [comment]
The above sample code will not maintain ARRAY dimensions. It will just give you the flat element sequence.

**Comment by seidlmic** [comment]
Thanks for reply I will have a look at proposed solutions.

**Comment by jwp** [comment]
Going to close this, if you have further questions, feel free to ask in this issue.
