### ISSUE TITLE
More flexible parameterized statements

### ISSUE THREAD

**Issue by seidlmic** [python-postgres/fe#112]
I am creating whole SQL in sequence of if-else statements which can result in something like this
```
sql = """
SELECT *
FROM a
WHERE x = $1 AND y = $3
"""
ps = db.prepare(sql)
ps(1, 2, 3)
```
But this returns postgresql.exceptions.IndeterminateTypeError. Is there any work around. It is quite difficult to re-index all parametrized statements. I see in other libraries non index version, just position or name based vesrion.

```
sql = """
SELECT *
FROM a
WHERE x = $ AND y = $
"""
ps = db.prepare(sql)
ps(1, 3)

or 

sql = """
SELECT *
FROM a
WHERE x = $x AND y = $y
"""
ps = db.prepare(sql)
ps(x=1, foo=2, y=3) or ps({x:1, foo:2, y:3})
```

**Comment by jwp** [comment]
I don't think so.

If you want to use parameterized statements and maintain the invariant at the SQL level, I think you will have to refer to `$2`.

```sql
SELECT ...
WHERE x = $1 AND y = $3 AND COALESCE($2::int = $2, TRUE)
```

Not sure if there's a more succinct way to consume `$2` or not. The transfer waste here is insignificant given low overhead(frequency or argument size). Given a high overhead, naturally, it would be preferable to drop the additional argument on the client side.

The alternative is to adjust the parameters (`$1` and `$2`) and discard the unwanted value using a lambda or equivalent:

```python
ps = db.prepare(...)
return (lambda x,y,z: ps(x,z))
```

The downsides here is that you have to adjust the indexes and the lambda ends up hiding the Statement instance. You'll have to choose the desired execution method at the point the lambda is created (`.rows, .__call__, .chunks`, etc).

Another alternative is packing the parameter set into a single value using JSON, hstore, or even ARRAY where
you would access the parameters relative to `$1`. The downside (or upside in some cases :) here is that you essentially circumvent the driver's type handling. This is similar to using symbolic parameters.

### Other Libraries

The examples you have given of alternative parameter forms both have their shortcomings in the context of this discussion.

The purely positional placeholders do not maintain the invariant (two parameters not three) and passing three arguments will either raise a TypeError(in python) or silently drop one of the arguments. It would, at least possibly, be ambiguous to the Statement interface which one should be dropped. Adding or removing placeholders would affect the statement's invocation signature.

The symbolically identified form has to make a similar choice. Drop the additional argument or raise an exception noting the reception of an unused argument. Presuming that it is acceptable for the Statement to drop arguments has risk. It could be the case that the wrong statement was being invoked. In fact, for consistency with Python's choice, it should raise a TypeError:

```python
def kwonly(kw1=1, kw2=2):
    return kw1 + kw2

kwonly(kw1=10, notaparam=50, kw2=20)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: kwonly() got an unexpected keyword argument 'notaparam'
```

Okay, so Python allows a sink, `**kw`, for the exceptions, but it *must* be explicitly stated.

### Generally

Personally, I consider the symbolic parameters (for both caller and callee) to be superior to indexed. While indexed is equally capable, you have to adhere to the constraint (normally) imposed by its succession on one side of the function or both. Conceptually, we're *strictly* interested in making the connection between a value held by the caller and a set of reference points in the callee.

The indexed form is likely reasonable as an implementation detail, but for human consumption? Not so much.


Closing, but feel free to followup.

**Comment by seidlmic** [comment]
Thanks for explanations. May be I did not explain my expectation clearly enough.
- I agree that number of placeholders and parameters have to be equal.
- I expect that passing parameters to prepared statement is defence against SQL injection
- I would appreciate possibility of positional or named syntax as it seems to me as more flexible
- As a workaround probably this syntax is also possible to consume $2 `($2 IN (NULL) IS NULL)`
- Finally I can manage in my if-else sequence to construct SQL with correctly indexed parameters. It is something like this, but this is what I would like to avoid
```
whereStr = 'WHERE a = $1'
sqlData = [a]
if b != None:
    whereStr += ' AND b = $2'
   sqlData.append(b)
elif c != None:
    whereStr += ' AND c = $3' if b != None else ' AND c = $2'
    sqlData.append(c)

sql = 'SELECT ..... {where}'.format(whereStr)
db.prepare(sql)(*sqlData)
```

**Comment by jwp** [comment]
py-postgresql is mostly interested in exposing what PostgreSQL offers via a Python interface. The dbapi20 driver has limited support for named parameters, but I would advise against its use.

The only way this driver will support positional or named syntax outside of dbapi20 is if PostgreSQL provided the feature itself.

When rendering a query in this fashion, an index state may be helpful:

```python
import itertools
def index_generator():
    for i in itertools.count(1):
        yield "$" + str(i)

def mkwhere(b):
    allocp = iter(index_generator()).__next__

    whereStr = 'WHERE a = ' + allocp()
    if b is not None:
        bparam = allocp()
        whereStr += ... + bparam

    whereStr += ... + allocp()

    return whereStr
```

**Comment by seidlmic** [comment]
Thanks for tip. Finally I have something like this
```python
sqlWhereTmpl = 'WHERE st.type = ${}'
sqlData = ['blue']

# more expression
if count != None:    
        sqlWhereTmpl += ' AND st.count = ${}'
        sqlData.append(count)

sqlWhere = sqlWhereTmpl.format(*range(1,len(sqlData)+1))
```
