### ISSUE TITLE
Cannot connect to Postgres 14.2 on Ubuntu

### ISSUE THREAD

**Issue by zx80** [python-postgres/fe#118]
On my Ubuntu 20.4 with Postgres 14.2 installed:

```Python
import postgresql.driver.dbapi20 as pg
c = pg.connect(database="tests", unix="/var/run/postgresql/.s.PGSQL.5432", host=None, port=None)
```

Results in:

*ValueError: invalid literal for int() with base 10: '2 (Ubuntu 14'*

Its seems that the driver is attempting to parse part of postgres version
`PostgreSQL 14.2 (Ubuntu 14.2-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit` as an integer.

**Comment by jwp** [comment]
The build of PostgreSQL that you are connecting to has modified the version string. You can resolve this problem by using a build of PostgreSQL that does not modify the version string or by patching the client to accept the variation. The patch can either be at runtime (override the version parsing function before establishing connections) or by modifying the source directly.
