### ISSUE TITLE
Connection Pool Servers and DuplicateCursorError / DuplicatePreparedStatementError

### ISSUE THREAD

**Issue by seidlmic** [python-postgres/fe#123]
Hello,
does anyone have experience with DuplicateCursorError? Actually I do not have knowledge with this topic. While on direct connection to PG I have never met this error with pgpool connect it sometimes happens. 

The error:
`
postgresql.exceptions.DuplicateCursorError: cursor "py:0x7fcd8a1405e0" already exists
`

The code is:
`
iterable_result = tuple(db.query.column("SELECT ...."))
`

The workaround:
`
result = db.query("SELECT ....")
iterable_result = [i[0] for i in result]
`

**Comment by jwp** [comment]
I'm not familiar with the mechanics of pgpool, so this is presuming the behavior of server based pools. I'm not sure how else this could happen outside of the pool discarding CloseStatement messages, which I doubt is happening here.

Explicit `close` on the statement objects *should* clear that up as well. py-postgresql will presume that connection termination means destruction of the backend process, and all prepared statements with it. With a pool, this might not be the case.

Forcing garbage collection before `Connection.close` may help in some cases as well(?). The goal is to get all the statement objects to a zero reference count before the disconnect message is sent to the server.

Correcting this behavior (wrt server based pools) is rather undesirable as it requires the connection to track all open statements. Even if such a correction were made, it would still be possible for interrupted connections (kill -9/close(connection-fd)) to cause the same exception. However, that is presuming the pool treats explicit disconnect messages the same.

**Comment by jwp** [comment]
Using `db.query` works because the statement is discarded immediately after execution(using the unnamed statement identifier iirc).

**Comment by jwp** [comment]
Okay, I read statements when cited exception reads cursor. However, it's essentially the same problem. Both cursors and statements can be leaked.

**Comment by jwp** [comment]
Using these system views may be a more durable solution:

- https://www.postgresql.org/docs/current/view-pg-prepared-statements.html
- https://www.postgresql.org/docs/current/view-pg-cursors.html

Prior to performing `Connection.close` or `Connection.__exit__`, explicitly close all the statements and cursors open in the session.

**Comment by jwp** [comment]
Now, as to why this is happening with cursors: either a transaction is being left open *or* the cursor is being created outside of a transaction block causing the driver to create the cursor WITH HOLD.

**Comment by seidlmic** [comment]
Looks like quite complicated topic. Actually I do not create any cursors explicitly I just use postgresql.open() and db.query(). Right know I have just remembered that also db.query.chunks() might have result in the same error with pgpool that I already replaced. Thanks for your time and explanation the error background.

**Comment by jwp** [comment]
Most statement execution methods allocate a Cursor object that will be held until exhausted or their transaction block is closed. IIRC, `PreparedStatement.__call__` will fetch the entire result set and close the cursor. Similar to `Connection.query`, but with named statement.

**Comment by jwp** [comment]
If the server pool is configured to interleave client queries on a shared connection, it gets slightly more complicated. The driver presumes exclusive access to a backend, so in order to share connections safely, the statement and cursor identifier generator need to be adjusted to include a "client identity" or the server pool needs to transparently make those adjustments itself.
