### ISSUE TITLE
Working with Threads

### ISSUE THREAD

**Issue by jwp** [python-postgres/fe#38]
Add a section to the driver documentation about working with threads. Most drivers offer thread safety, but driver.pq3 does not.

Discuss: one connection per thread, synchronizing using a queue, and explicit locking.

**Comment by seidlmic** [comment]
Hello, I would like to ask if it is still true that to establish and close connection inside threads is OK?

**Comment by jwp** [comment]
Should be. However, when closing a Connection, only one thread should be performing the operation.

**Comment by seidlmic** [comment]
Hm, not very clear to me. I have one main thread that creates and starts child threads in unpredictable time (all at ones, one after another, overlapping in some way). In each child thread I create separate db connection by calling `postgresql.open()` and perform queries with `db.query(), db.prepare()`. What do you mean "_However, when closing a Connection, only one thread should be performing the operation_"?

- I can not rely on Python garbage cleaning when exiting thread code?
- If I have to close db connection with `db.close()`, closing one connection can in some way interact with connections from other threads? I am afraid there is no way to do it as threads are completely time independent. They can start and end any time.

**Comment by jwp** [comment]
> I can not rely on Python garbage cleaning when exiting thread code?

If you rely on garbage collection, I believe a resource warning will be emitted by Python's socket module.
Doing so will only cause the socket to be closed and no termination message will be issued to the server.
I would not advise relying on garbage collection for Connection close.

> If I have to close db connection with db.close(), closing one connection can in some way interact with connections from other threads? I am afraid there is no way to do it as threads are completely time independent. They can start and end any time.

No. The driver is not thread aware and there is no communication between connections. You can either `db.close()` or `with db:`, but *only one thread should be performing the operation on a single Connection*. Sharing a single Connection across multiple threads is not safe unless operations are protected by a synchronization primitive.

If each thread has its own Connection, you're safe.

**Comment by jwp** [comment]
Use the issue as documentation.

**Comment by seidlmic** [comment]
Hello, after one year with happy usage of model "connection per thread" new error sometimes rises. It looks like it always happens at the very beginning when the multiple threads start at the same time. The error looks like this:
```
  File "/usr/local/gabina/venv/m_backupSchema-2.1.2/lib/python3.11/site-packages/postgresql/__init__.py", line 74, in open
    std_params = _pg_param.collect(prompt_title = None)
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'collect'
```
Can it be some race condition with importing pypostgresql library? Should be imported in main thread or child thread?

https://github.com/python-postgres/fe/blob/1cd1b4476739fbcb0dc840fe5a2260209eba75c6/postgresql/__init__.py#L37C1-L37C40

**Comment by jwp** [comment]
_pg_param is the last global initialized and _pg_iri is the first, so I think so. Naturally, this will only occur if you're using postgresql.open. Using Connectors directly instead of postgresql.open is advisable for most applications.

Workarounds:
- Perform one postgresql.open prior to launching any threads.
- Fill in the globals manually(_pg_param, _pg_iri, _pg_driver).
- Patch __init__.py to check all globals (planned fix for this)

The deferred imports, likely, don't have any value these days. They were used to avoid unused modules in applications that used Connectors directly. Today, the primary advantage this has is dodging bitrot in _pg_param.

The third workaround is what I plan to apply. Remaining synchronization issues should be handled by Python's import locks and object level locks in nogil Pythons.

**Comment by seidlmic** [comment]
Thanks for advice we have changed open() with driver.connect() and problem is gone :)
