### ISSUE TITLE
allow connection to unix domain sockets via 'pq://' locator strings

### ISSUE THREAD

**Issue by avbidder** [python-postgres/fe#53]
I'm not sure if this is a wishlist bug or a documentation bug.

I'd like to connect to my database via unix socket.  How should my locator string look like?  (I'd really like to use a locator string, since I then can just read that string from the configuration)

Ideally: 'pq:///' would just connect to the default database by the default unix socket that is used on my OS.  'pq:///dbname' would be the obvious way to specify a database.  Not sure about a syntax when my unix socket is not at the default location.

**Comment by jwp** [comment]
Already available.
