### ISSUE TITLE
Compatibility with Amazon Redshift

### ISSUE THREAD

**Issue by kruser** [python-postgres/fe#72]
Amazon Redshift uses a slightly modified PostgreSQL leader node for access, so any postgres ODBC client should be able to connect.

However, using this library to connect I get the following error.

```
    postgresql.exceptions.InsufficientPrivilegeError: permission denied to set parameter "client_min_messages" to "WARNING"
      CODE: 42501
      LOCATION: File '/home/awsrsqa/padb/src/pg/src/backend/utils/misc/guc.c', line 6127, in set_config_option from SERVER
```

Is there a flag that I can set when making the connection to keep this from happening?

**Comment by bluesmoon** [comment]
So does this mean that we cannot use this library with Redshift since it doesn't appear that Amazon has any interest in fixing this.

**Comment by blade2005** [comment]
This issue is closed but I believe work does still need to be done in terms of filtering None items and removing those items. Might require two passes over the dict. One to set everything then another to remove any None items. 

But I came across this project due to using AWS Lambda and Lambda with psycog doesn't work because compiled C code. 

Apparently this project may not be suitable without additional code. @kruser what native lib did you use?

**Comment by kruser** [comment]
@blade2005 - we use psycopg2 version 2.5.3.

**Comment by jwp** [comment]
Aside from using another driver, patching py-postgresql locally is a reasonable solution. I believe it's a one line change.

**Comment by jwp** [comment]
This line: https://github.com/python-postgres/fe/blob/33465976b275e92236d1d4a3c38e3c5639deca9d/postgresql/driver/pq3.py#L2798

And if that doesn't work, clear the tnkw dictionary after the "settings" parameter is applied.

**Comment by blade2005** [comment]
@kruser darn. That library uses C code which I tried and isn't working on AWS Lambda. It's why I was looking for a pure python solution. 

I guess I'm going to have to patch it locally.

**Comment by mouchar** [comment]
Sorry for writing to old, closed issue, but some people could find my solution useful (no library patching required):
```python
import postgresql

# These 2 lines are needed only for single-node Redshift deployments
from postgresql.driver.pq3 import MultiXactStream
MultiXactStream.chunksize = 1000

# when starting url with '&', like '&pq://localhost/mydb', the library returns Connector
conn_f = postgresql.open('&'+db_url, ....)

# Remove offending parameter, keeping others unmodified
conn_f._startup_parameters = tuple([v for v in conn_f._startup_parameters
                                    if v[0] != b'client_min_messages'])

# Create Connection
db = conn_f()
db.connect()

# Run Redshit queries as usual
db.query('SELECT * FROM mytable')
```

I understand this solution is not very clean, but it works fine for my needs.
Anyway, thank you for all the effort you make to maintain this marvelous library :clap:

**Comment by jwp** [comment]
Despite being an old issue, this still gets a little traffic. If you're interested in having an easier and builtin form of what @mouchar posted, give this comment a thumb's up. Been doing a little house keeping lately and if I can find a non-intrusive way to fit it in, I will.
