### ISSUE TITLE
Named parameters

### ISSUE THREAD

**Issue by gintsmurans** [python-postgres/fe#78]
Hi!
Are you planning on implementing named parameters in prepare method?

**Comment by jwp** [comment]
Not in the direct interface. The DB-API driver has some support for this using percent escapes such as: `%(keyword)s`, but it has to use some regular expressions to parse the SQL string. The code that performs the processing is addressable: `postgresql.driver.dbapi20.Cursor._convert_query(None, "SQL...")` and can be used independently of the DB-API interface if so desired. Just look around postgresql/driver/dbapi20.py for its invocation, and it should be somewhat obvious how to use it to transform the statement and map the parameters for positional application. However, this is not really a recommendation. Rather, using the native positional parameters directly or with generated queries is ideal.
