### ISSUE TITLE
Unsupported JSONB version number 123

### ISSUE THREAD

**Issue by Mayzie** [python-postgres/fe#79]
Using Python 3.5, and PostgreSQL 9.5, when trying to call a stored procedure which has a data type which is JSONB, I get the following exception thrown:

> unsupported jsonb version number 123
>   CODE: XX000
>   LOCATION: File 'jsonb.c', line 122, in jsonb_recv from SERVER
> RESULT:
>   type: SingleXactFetch
>   parameters:
>     ('{af41ddf7-da70-4d18-b217-f279ad1eb6c6}', 'Test', None, None, '{"test": "data"}', None, None)
> STATEMENT: [prepared]
>   sql_parameter_types:
>     ['pg_catalog.uuid', 'pg_catalog.text', '"XXXXXXXXXX"."_objectflags"', 'INTEGER', '"pg_catalog"."jsonb"', 'pg_catalog.text', 'pg_catalog.uuid']
>   results: ('func' 'BOOLEAN')
>   statement_id: py:0x7ff27900c4a8
>   string:
>     SELECT * FROM XXXXXXXXXXX.updateuser($1::pg_catalog.uuid, $2::pg_catalog.text, $3::"XXXXXXXXXXX"."_objectflags", $4::INTEGER, $5::"pg_catalog"."jsonb", $6::pg_catalog.text, $7::pg_catalog.uuid) AS func
> CONNECTION: [idle]
>   client_address: ::1/128
>   client_port: 38546
>   version:
>     PostgreSQL 9.5.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 6.1.1 20160802, 64-bit
> CONNECTOR: [Host] pq://XXXXXXXXXX:***@localhost:5432/XXXXXXXXXX
>   category: None
> DRIVER: postgresql.driver.pq3.Driver

Distribution: Arch Linux (amd64)

**Comment by Mayzie** [comment]
I was using the (apparently not) latest version, v1.1 (from `pip install py-postgresql`). I noticed in the commit history that JSONB support is relatively recent, so I installed the code base from the `master` branch.  Upon doing so, now where I go to register the stored procedures, now I'm getting the following error:

```
syntax error at or near "None"
  CODE: 42601
  LOCATION: File 'scan.l', line 1081, in scanner_yyerror from SERVER
  POSITION: 135
STATEMENT: [parsing]
  LINE:
    SELECT * FROM XXXXXXXXX.YYYYYYYYYYY($1::pg_catalog.uuid, $2::pg_catalog.text, $3::"XXXXXXXXX"."_objectflags", $4::INTEGER, $5::None, $6::pg_catalog.text, $7::pg_catalog.uuid) AS func
                                                                                                                                  ^ [line 1, character 135]

```

whereas before, in version 1.1, it worked.

The data type at $5, should really be JSONB, but for some reason it is None.

**Comment by jwp** [comment]
Was fairly certain there were tests with the JSONB work, but I didn't go over it in detail. There was another issue with 3.5 (it didn't like the syntax used for builtins caching) so the latest release tag needed some more work; partially why v1.1.1 isn't on PyPI yet.

**Comment by jwp** [comment]
I was able to reproduce this. OID to name was missing for json and jsonb. I think we fallback to querying for the name when we don't recognize the OID, but in this case it was registered in one part of the type I/O system, so it presumed that it was available in the other part.

**Comment by jwp** [comment]
Fix was pushed to master. Thanks for the report.
