### ISSUE TITLE
Remove pgfoundry site and projects.

### ISSUE THREAD

**Issue by jwp** [python-postgres/fe#86]
github pages will suffice. However, I haven't been able to get them to remove other projects so it may end up being a redirect to the github.io site.

**Comment by phdru** [comment]
http://python.projects.postgresql.org redirects to http://python.projects.pgfoundry.org/ which is not available (DNS error). Shouldn't it be fixed? Possible replacements are http://pgfoundry.org/projects/python/ or https://github.com/python-postgres

Pages where http://python.projects.postgresql.org is mentioned:
- https://github.com/python-postgres (at the top);
- https://github.com/python-postgres/be (at the top);
- https://github.com/python-postgres/fe (at the top and in README);
- https://github.com/python-postgres/web (at the top);
- https://pypi.python.org/pypi/py-postgresql (generated from [/postgresql/release/distutils.py](https://github.com/python-postgres/fe/blob/master/postgresql/release/distutils.py)).
- https://github.com/python-postgres/fe/blob/master/postgresql/project.py

**Comment by jwp** [comment]
It could be an outage, but might as well start removing links.

**Comment by phdru** [comment]
Doesn't look like a temporary outage.

**Comment by jwp** [comment]
Documentation now available at py-postgresql.readthedocs.io. I think most links have been updated. Not sure when/if I'll get around to making a pretty github page.
