### ISSUE TITLE
Inline binary data

### ISSUE THREAD

**Issue by phdru** [python-postgres/fe#87]
I'm using a library that doesn't work with parameters so I have to generate all queries as complete strings. Now I need to pass binary data, i.e. a byte string (array of bytes). Can I do it? How?

This is how I do it with other drivers.

psycopg2:
```python
#! /usr/bin/env python

import psycopg2

sqlStringReplace = [
    ("'", "''"),
    ('\\', '\\\\'),
    ('\000', '\\0'),
    ('\b', '\\b'),
    ('\n', '\\n'),
    ('\r', '\\r'),
    ('\t', '\\t'),
]

def quote(value):
    for orig, repl in sqlStringReplace:
        value = value.replace(orig, repl)
    if '\\' in value:
        return "E'%s'" % value
    return "'%s'" % value

test_data = bytes(range(256))

con = psycopg2.connect(database="test")
cur = con.cursor()
cur.execute("CREATE TABLE test (id serial, test varchar)")
cur.execute("INSERT INTO test VALUES (1, %s)" %
            quote(str(psycopg2.Binary(test_data))))
cur.execute("SELECT * FROM test ORDER BY id")
for rec in cur.fetchall(): print(rec[1])
```
Output:
```python
'\000\001\002\003\004\005\006\007\010\011\012\013\014\015\016\017\020\021\022\023\024\025\026\027\030\031\032\033\034\035\036\037 !"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\177\200\201\202\203\204\205\206\207\210\211\212\213\214\215\216\217\220\221\222\223\224\225\226\227\230\231\232\233\234\235\236\237\240\241\242\243\244\245\246\247\250\251\252\253\254\255\256\257\260\261\262\263\264\265\266\267\270\271\272\273\274\275\276\277\300\301\302\303\304\305\306\307\310\311\312\313\314\315\316\317\320\321\322\323\324\325\326\327\330\331\332\333\334\335\336\337\340\341\342\343\344\345\346\347\350\351\352\353\354\355\356\357\360\361\362\363\364\365\366\367\370\371\372\373\374\375\376\377'::bytea
```

PyGreSQL:
```python
#! /usr/bin/env python

from pg import escape_bytea, unescape_bytea
import pgdb

sqlStringReplace = [
    ("'", "''"),
    ('\\', '\\\\'),
    ('\000', '\\0'),
    ('\b', '\\b'),
    ('\n', '\\n'),
    ('\r', '\\r'),
    ('\t', '\\t'),
]

def quote(value):
    for orig, repl in sqlStringReplace:
        value = value.replace(orig, repl)
    if '\\' in value:
        return "E'%s'" % value
    return "'%s'" % value

test_data = bytes(range(256))

con = pgdb.connect(database="test")
cur = con.cursor()
cur.execute("CREATE TABLE test (id serial, test varchar)")
cur.execute("INSERT INTO test VALUES (1, %s)" %
            quote(escape_bytea(test_data).decode('latin1')))
cur.execute("SELECT * FROM test ORDER BY id")
for rec in cur.fetchall(): print(unescape_bytea(rec[1]))
```
Output:
```python
b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\x7f\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff'
```

**Comment by jwp** [comment]
This is the appropriate way to pass binary parameters in with py-postgresql's DB-API 2.0 driver:

```
>>> c.execute("SELECT %(param)s::bytea;", dict(param=b'raw-data\x00\x01')).fetchall()
[(b'raw-data\x00\x01',)]
```

You'll want to be sure to use the bytea type as the column type when creating your table.

**Comment by phdru** [comment]
Thanks but that doesn't help. As I said at the start I cannot use query parameters, i.e. I have to pass an SQL query string to cursor.execute() but not the other arguments. Like this:
```python
c.execute("SELECT '%s'::bytea;" % b'raw-data\x00\x01')
```
This means I have to quote/escape binary data myself. How can I do that? The followin doesn't work:
```python
#! /usr/bin/env python

from postgresql.driver import dbapi20

sqlStringReplace = [
    ("'", "''"),
    ('\\', '\\\\'),
    ('\000', '\\0'),
    ('\b', '\\b'),
    ('\n', '\\n'),
    ('\r', '\\r'),
    ('\t', '\\t'),
]

def quote(value):
    for orig, repl in sqlStringReplace:
        value = value.replace(orig, repl)
    if '\\' in value:
        return "E'%s'" % value
    return "'%s'" % value

test_data = ''.join([chr(x) for x in range(256)])

con = dbapi20.connect(database="test", host=None, port=None,
                      unix='/var/run/postgresql/.s.PGSQL.5432')
cur = con.cursor()
cur.execute("CREATE TABLE test (id serial, test bytea)")
cur.execute("INSERT INTO test VALUES (1, %s::bytea)" %
            quote(test_data))
```
Error:
```
Traceback (most recent call last):
  File "./test1.py", line 29, in <module>
    quote(test_data))
  File ".../lib/python3.4/site-packages/postgresql/driver/dbapi20.py", line 271, in execute
    ps = self.database.prepare(sql)
  File ".../lib/python3.4/site-packages/postgresql/driver/pq3.py", line 2330, in prepare
    ps._init()
  File ".../lib/python3.4/site-packages/postgresql/driver/pq3.py", line 1488, in _init
    q = self.database.typio._encode(str(self.string))[0]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 165-292: ordinal not in range(128)
```

**Comment by jwp** [comment]
I think there are two ways to go about this. Circumvent client query encoding by creating your own Statement._init implementation or by extending your escape function to escape high and low ASCII. I'd recommend the latter. Likely a variant of the following:

```
escape = (lambda string: ''.join(['\\'+(x[2:].rjust(3, '0')) for x in (oct(ord(y)) for y in string)]))
```

However, the above is not efficient.

**Comment by jwp** [comment]
Might be missing some backslashes in the escape function...

**Comment by phdru** [comment]
I see, thank you! This mean there is no the right way to do escaping and I have to invent my own scheme. In that case it's simpler to go with base64, I think.

**Comment by phdru** [comment]
@jwp Your `escape()` function works and produces the same data in database as psycopg2 and PyGreSQL. I'm gonna use it in my library. Seems it's universal enough to be used with drivers that don't do escaping themselves (I'm also gonna use pg8000).

If you don't mind I'll list James William Pye <james.pye at gmail> as a contributor to the library.

**Comment by jwp** [comment]
No need to list me; I didn't submit a patch nor did I provide tests(arguably the most important part of a submission). Not to mention, I actually recommend *against* using it with character data altogether. Given that Python is complaining about that test data being invalid for the encoding, I'd be concerned about the data's portability. This may not be a concern for you or your application, but support for client side encoding is arguably a minor feature of py-postgresql (rather, a given considering unicode strings) and circumventing it this way is a suspicious practice that will likely lead to problems. Notably, character data that you put into the database may not be retrievable without using escapes or casting to bytea.

**Comment by jwp** [comment]
Well, the above may not be entirely true, using escapes to circumvent *desired* limitations of a configured client_encoding may be reasonable at times. The above is essentially presuming that the client_encoding is consistent with the server_encoding and therefore using escapes to undermine the restrictions would likely lead to problems if not immediate server errors. The presumption is reasonable in the context of Python as it has support for frequently used encodings.

**Comment by phdru** [comment]
The encoding is only applied to binary data, not characters. The patch is [here](https://github.com/sqlobject/sqlobject/commit/ecccd99cbf60031312e48ebd6736bf8235dca042), the [tests](https://travis-ci.org/sqlobject/sqlobject/builds/237299886) for pypostgresql are now green (they were failing for many months). Mission accomplished, thank you very much!

**Comment by jwp** [comment]
Oh! Yes, full escaping is reasonable in that case. =)
There is, naturally, a performance penalty on both the client and the server, but if portability is the primary concern, it's a good solution. Any ASCII compatible client_encoding should accept it without issue.
