### ISSUE TITLE
list index out of range in types in 1.2.1 (proc)

### ISSUE THREAD

**Issue by mc3** [python-postgres/fe#89]
After upgrading from 1.1.0, I'm getting

File "/usr/local/etc/erdb_bt/db/host.py", line 127, in insertHost
   proc_record_Relay = dbe.proc('record_Relay(text, text, boolean, int)')
 File "/usr/local/lib/python3.4/site-packages/postgresql/driver/pq3.py", line 2345, in proc
   sp = StoredProcedure(proc_id, self)
 File "/usr/local/lib/python3.4/site-packages/postgresql/driver/pq3.py", line 1920, in __init__
   for x in range(1, len(proargs)+1)
 File "/usr/local/lib/python3.4/site-packages/postgresql/driver/pq3.py", line 1920, in <listcomp>
   for x in range(1, len(proargs)+1)
 File "/usr/local/lib/python3.4/site-packages/postgresql/types/__init__.py", line 509, in __getitem__
   return self._elements[item]
IndexError: list index out of range

operations=# \df record_Relay
                                                         List of functions
 Schema |     Name     | Result data type |                              Argument data types                              |  Type  
--------+--------------+------------------+-------------------------------------------------------------------------------+--------
 erdb   | record_relay | record_relay_rtt | relay_ip text, relay_fqdn text, countconnection boolean, rdns_invalid integer | normal

**Comment by Mayzie** [comment]
Revert commit 3346597 , then it will work.

@jwp

**Comment by jwp** [comment]
Sorry about this. I believe the problem stemmed from me managing to run the tests against an older build, but I'm not sure how. Naturally, it was bewildering seeing this bug when I had just seen the tests pass.

There is some maintenance work to be done with newer versions of PG and Python which caused me to look at my bug list again.
