### ISSUE TITLE
not pack parameter timestamp

### ISSUE THREAD

**Issue by marcioacmauricio** [python-postgres/fe#99]
I'm trying to run the query through the py-postgresql library and the library is not handling the timestamp parameter
"could not pack parameter $4::TIMESTAMP WITHOUT TIME ZONE for transfer"

INSERT INTO public.example
	(ordering, state, checked_out, checked_out_time, created_by, modified_by, name, cep, cpf, cnpj, birth_day, hora_cadastro, email, username, phone_number, website, client_type, user_id, data_bloqueio, user2_id, description) 
	VALUES 
	($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
could not pack parameter $4::TIMESTAMP WITHOUT TIME ZONE for transfer
[
    1,
    1,
    1,
    "2018-01-01 01:01:01",
    1,
    1,
    "Marcio Mauricio",
    "29193-118",
    "078.100.137-42",
    "08.832.573/0001-93",
    "2018-06-06",
    "10:00:00",
    "marcioacmauricio@gmail.com",
    "marcioacmauricio",
    "(27) 99688-4577",
    "http://www.teste.com",
    1,
    1,
    "2018-02-22 10:10:00",
    1,
    "descri\u00e7\u00e3o do item"
]

**Comment by marcioacmauricio** [comment]
I managed to resolve past the date as an object and not a string
objDate = datetime.strptime(DateTime, '%d/%m/%Y %H:%M:%S')

**Comment by jwp** [comment]
I imagine the timestamp was being passed as a builtins.str object. Another alternative would be to cast the parameter as TEXT and then as a TIMESTAMP. This is a feature of the driver providing conversions from Python types to Postgres types(and the reverse). A common means to circumvent the feature is to cast a parameter or column as TEXT.
